### ISSUE TITLE
resources video : 500 dans l'API

### ISSUE THREAD

**Issue by paulgirard** [medialab/aime-core#172]
si on crée une video sans ref bibilo : 
Uncaught TypeError: Cannot read property 'biblib_id' of null

Même erreur pour les liens (kind:link)

si on crée sans une vidéo : 
erreur 500  sur http://localhost:7000/res/video
TypeError: Generator is already running
    at throw (native)
    at next (/home/pgi/dev/aime-core/node_modules/co/index.js:65:26)
    at Essence.next (/home/pgi/dev/aime-core/node_modules/co/index.js:106:7)
    at /home/pgi/dev/aime-core/node_modules/co/index.js:93:18
    at Request._callback (/home/pgi/dev/aime-core/node_modules/essence/lib/provider.js:84:5)
    at Request.self.callback (/home/pgi/dev/aime-core/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pgi/dev/aime-core/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)

**Comment by Yomguithereal** [comment]
TL;DR: ne pas utiliser node v6 avec le flag `harmony`.

**Comment by paulgirard** [comment]
bug seulement en node v6 mode harmony...
